/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'processing' : IDL.Null,
});
export const Time = IDL.Int;
export const CustomOrder = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'productId' : IDL.Nat,
  'timestamp' : Time,
  'quantity' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'retailPrice' : IDL.Float64,
  'name' : IDL.Text,
  'wholesalePrice' : IDL.Float64,
  'description' : IDL.Text,
  'supplierId' : IDL.Nat,
});
export const Supplier = IDL.Record({
  'id' : IDL.Nat,
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Float64, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'addSupplier' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'calculateProductProfit' : IDL.Func([IDL.Nat], [IDL.Float64], ['query']),
  'createOrder' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'getAllOrdersSortedByTimestamp' : IDL.Func(
      [],
      [IDL.Vec(CustomOrder)],
      ['query'],
    ),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllSuppliers' : IDL.Func([], [IDL.Vec(Supplier)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [CustomOrder], ['query']),
  'getSupplierProducts' : IDL.Func([IDL.Nat], [IDL.Vec(Product)], ['query']),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'processing' : IDL.Null,
  });
  const Time = IDL.Int;
  const CustomOrder = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'productId' : IDL.Nat,
    'timestamp' : Time,
    'quantity' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'retailPrice' : IDL.Float64,
    'name' : IDL.Text,
    'wholesalePrice' : IDL.Float64,
    'description' : IDL.Text,
    'supplierId' : IDL.Nat,
  });
  const Supplier = IDL.Record({
    'id' : IDL.Nat,
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Float64, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'addSupplier' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'calculateProductProfit' : IDL.Func([IDL.Nat], [IDL.Float64], ['query']),
    'createOrder' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [IDL.Nat], []),
    'getAllOrdersSortedByTimestamp' : IDL.Func(
        [],
        [IDL.Vec(CustomOrder)],
        ['query'],
      ),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllSuppliers' : IDL.Func([], [IDL.Vec(Supplier)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [CustomOrder], ['query']),
    'getSupplierProducts' : IDL.Func([IDL.Nat], [IDL.Vec(Product)], ['query']),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };