/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CustomOrder {
  'id' : bigint,
  'customerName' : string,
  'status' : OrderStatus,
  'productId' : bigint,
  'timestamp' : Time,
  'quantity' : bigint,
}
export type OrderStatus = { 'shipped' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'processing' : null };
export interface Product {
  'id' : bigint,
  'retailPrice' : number,
  'name' : string,
  'wholesalePrice' : number,
  'description' : string,
  'supplierId' : bigint,
}
export interface Supplier {
  'id' : bigint,
  'contactInfo' : string,
  'name' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'addProduct' : ActorMethod<[string, string, bigint, number, number], bigint>,
  'addSupplier' : ActorMethod<[string, string], bigint>,
  'calculateProductProfit' : ActorMethod<[bigint], number>,
  'createOrder' : ActorMethod<[bigint, bigint, string], bigint>,
  'getAllOrdersSortedByTimestamp' : ActorMethod<[], Array<CustomOrder>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllSuppliers' : ActorMethod<[], Array<Supplier>>,
  'getOrder' : ActorMethod<[bigint], CustomOrder>,
  'getSupplierProducts' : ActorMethod<[bigint], Array<Product>>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];